/**
 * @irich/core
 * Framework-independent component definition schema and declaration helper.
 * Strictly decoupled from React and DOM execution environments.
 */

import { InvalidComponentError } from '../errors';
import type { IRichNode, JSONValue } from '../types';
import type { FieldDefinition } from './fields';

/**
 * Slot / Dropzone specification for nesting child components inside multi-zone layouts.
 */
export interface SlotDefinition {
  /**
   * Human-readable label displayed in visual editor breadcrumbs and outlines.
   */
  readonly label?: string;

  /**
   * Optional array of component type names permitted in this slot.
   * If omitted, any registered component type can be placed here.
   */
  readonly allowedTypes?: readonly string[];

  /**
   * Maximum number of child nodes permitted in this slot.
   */
  readonly maxChildren?: number;
}

/**
 * Declarative blueprint specification for scaffolded initial child nodes.
 * Does not require specifying IDs, which are automatically generated upon instantiation.
 */
export interface InitialChildBlueprint {
  readonly type: string;
  readonly props?: Record<string, JSONValue>;
  readonly children?: readonly InitialChildBlueprint[];
  readonly slots?: Readonly<Record<string, readonly InitialChildBlueprint[]>>;
}

/**
 * Initial structural state and properties returned by a component's `createInitialState` factory.
 */
export interface ComponentInitialState<
  Props extends Record<string, JSONValue> = Record<string, JSONValue>,
> {
  readonly props?: Partial<Props>;
  readonly children?: readonly (InitialChildBlueprint | IRichNode)[];
  readonly slots?: Readonly<Record<string, readonly (InitialChildBlueprint | IRichNode)[]>>;
}

/**
 * Framework-independent component specification in iRich.
 * Contains purely serializable schema, field descriptors, and metadata.
 */
export interface ComponentDefinition<
  Props extends Record<string, JSONValue> = Record<string, JSONValue>,
> {
  /**
   * Unique component type identifier (matches `node.type`).
   */
  readonly type: string;

  /**
   * Human-readable title shown in component palettes and inspector headers.
   */
  readonly label: string;

  /**
   * Optional category grouping in block pickers (e.g. 'Marketing', 'Layout', 'Typography').
   */
  readonly category?: string;

  /**
   * Optional description of the component's purpose.
   */
  readonly description?: string;

  /**
   * Optional icon identifier or name.
   */
  readonly icon?: string;

  /**
   * Declarative fields / prop schemas used for inspector generation and prop validation.
   */
  readonly fields: Record<string, FieldDefinition>;

  /**
   * Optional default props assigned upon insertion.
   * Merged with individual field default values.
   */
  readonly defaultProps?: Partial<Props>;

  /**
   * Optional named slot definitions for nesting child components.
   */
  readonly slots?: Readonly<Record<string, SlotDefinition>>;

  /**
   * Whether this component can accept child components.
   * If false, dropping children directly inside this component's default children array is prohibited.
   * Defaults to true if not specified.
   */
  readonly canHaveChildren?: boolean;

  /**
   * Whitelist of component types permitted as direct children.
   * If omitted, any registered component type can be placed inside (unless restricted by child rules).
   */
  readonly allowedChildren?: readonly string[];

  /**
   * Whitelist of component types permitted as direct parents.
   * If omitted, this component can be placed inside any container component or the root.
   */
  readonly allowedParents?: readonly string[];

  /**
   * Optional factory returning initial structural state, props, and default child scaffolding.
   * Invoked when creating new instances from component pickers or palette drag-and-drop.
   * IDs for any scaffolded child blueprints are safely generated by the core engine.
   */
  readonly createInitialState?: () => ComponentInitialState<Props>;

  /**
   * Non-rendered component metadata or tags.
   */
  readonly meta?: Readonly<Record<string, JSONValue>>;
}

/**
 * Declares and validates a framework-independent component definition.
 *
 * @example
 * ```typescript
 * export const HeroComponent = defineComponent({
 *   type: 'Hero',
 *   label: 'Hero Section',
 *   category: 'Marketing',
 *   fields: {
 *     title: { type: 'text', label: 'Title', defaultValue: 'Hello World' },
 *     alignment: {
 *       type: 'select',
 *       options: [
 *         { label: 'Left', value: 'left' },
 *         { label: 'Center', value: 'center' },
 *       ],
 *     },
 *   },
 * });
 * ```
 */
export function defineComponent<
  Props extends Record<string, JSONValue> = Record<string, JSONValue>,
>(definition: ComponentDefinition<Props>): ComponentDefinition<Props> {
  if (!definition || typeof definition !== 'object') {
    throw new InvalidComponentError('Component definition must be a non-null object.');
  }

  if (!definition.type || typeof definition.type !== 'string' || !definition.type.trim()) {
    throw new InvalidComponentError('Component definition must have a non-empty string "type".');
  }

  if (!definition.label || typeof definition.label !== 'string' || !definition.label.trim()) {
    throw new InvalidComponentError(
      `Component definition "${definition.type}" must have a non-empty string "label".`,
    );
  }

  if (
    !definition.fields ||
    typeof definition.fields !== 'object' ||
    Array.isArray(definition.fields)
  ) {
    throw new InvalidComponentError(
      `Component definition "${definition.type}" must have a "fields" record object.`,
    );
  }

  return Object.freeze({
    ...definition,
    fields: Object.freeze({ ...definition.fields }),
    defaultProps: definition.defaultProps
      ? Object.freeze({ ...definition.defaultProps })
      : undefined,
    slots: definition.slots ? Object.freeze({ ...definition.slots }) : undefined,
    meta: definition.meta ? Object.freeze({ ...definition.meta }) : undefined,
  });
}
